name: drpclock
description: Aplicación de control de asistencia y registro de horas de trabajo.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  google_sign_in: ^6.1.6
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  provider: ^6.1.1
  flutter_local_notifications: ^16.2.0
  permission_handler: ^11.1.0
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  printing: ^5.11.1
  open_file: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ 